excluded: # шляхи, які слід виключити з перевірки
    - Carthage
    - Pods
    - build/
    - Superforivtsi/Features/HelpEachOther/Models
    - Superforivtsi/Data/Network/Routes
    
disabled_rules: # правила, які слід відключити
    - trailing_whitespace
    - line_length
    - cyclomatic_complexity
    - function_body_length
    - file_length
    - type_body_length
    - type_name
    - identifier_name

opt_in_rules: # додаткові правила, які не включені за замовчуванням
    - force_unwrapping
    - force_cast
    # - explicit_type_interface
    - private_outlet
    - empty_count
    - missing_docs
    - closure_spacing
    - collection_alignment
    - implicitly_unwrapped_optional
    - no_extension_access_modifier
    - operator_usage_whitespace

line_length: 120

vertical_whitespace:
    max_empty_lines: 2
large_tuple:
    warning: 3
    error: 4
line_length:
    warning: 250
    error: 500
function_parameter_count:
    warning: 10
    error: 11

custom_rules:
    missing_docs:
        included: ".*.swift"
        regex: '\n *(?!\/\/\/)(\/\/)?[^\n\/]*\n *(?:@\S+ )*(?:public |open )'
        name: "Missing Docs"
        message: "Types, properties and methods with public or open access level should be documented."
        severity: warning

custom_rules:
  no_direct_init:
    name: "No Direct Init"
    regex: '\.(?!super)\binit\b\((?!(\s*|\())'
    match_kinds: [identifier]
    message: "Direct use of .init() detected, use type inference instead."
    severity: warning
    
reporter: "xcode" # формат виводу SwiftLint
